linters-settings:
  dupl:
    threshold: 300
  lll:
    line-length: 160
  gomnd:
    checks:
      - argument
      - case
      - condition
      - return
  gosec:
    excludes:
      - G404
linters:
  enable:
    - errcheck
    - dogsled
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - depguard
    - dupl
    - goconst
    - lll
    - noctx
    - gomnd
    - gosec
    - revive
#    - goimports          # Check import statements are formatted according to the 'goimport' command
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - goconst
        - lll
run:
  timeout: 5m
  go: "1.19"
  modules-download-mode: readonly
  skip-dirs: []