// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IDeleteRepository is an autogenerated mock type for the IDeleteRepository type
type IDeleteRepository[T interface{}] struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, param
func (_m *IDeleteRepository[T]) Delete(ctx context.Context, param *T) error {
	ret := _m.Called(ctx, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIDeleteRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIDeleteRepository creates a new instance of IDeleteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIDeleteRepository[T interface{}](t mockConstructorTestingTNewIDeleteRepository) *IDeleteRepository[T] {
	mock := &IDeleteRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
