// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IHttpClient is an autogenerated mock type for the IHttpClient type
type IHttpClient struct {
	mock.Mock
}

// MakeRequest provides a mock function with given fields: obj
func (_m *IHttpClient) MakeRequest(obj interface{}) error {
	ret := _m.Called(obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIHttpClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewIHttpClient creates a new instance of IHttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHttpClient(t mockConstructorTestingTNewIHttpClient) *IHttpClient {
	mock := &IHttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
