// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aasumitro/pokewar/domain"
	mock "github.com/stretchr/testify/mock"
)

// IMonsterRepository is an autogenerated mock type for the IMonsterRepository type
type IMonsterRepository struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx, args
func (_m *IMonsterRepository) All(ctx context.Context, args ...string) ([]*domain.Monster, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*domain.Monster
	if rf, ok := ret.Get(0).(func(context.Context, ...string) []*domain.Monster); ok {
		r0 = rf(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Monster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx
func (_m *IMonsterRepository) Count(ctx context.Context) int {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, param
func (_m *IMonsterRepository) Create(ctx context.Context, param []*domain.Monster) error {
	ret := _m.Called(ctx, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Monster) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, param
func (_m *IMonsterRepository) Update(ctx context.Context, param *domain.Monster) error {
	ret := _m.Called(ctx, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Monster) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIMonsterRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMonsterRepository creates a new instance of IMonsterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMonsterRepository(t mockConstructorTestingTNewIMonsterRepository) *IMonsterRepository {
	mock := &IMonsterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
