// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IParamParser is an autogenerated mock type for the IParamParser type
type IParamParser struct {
	mock.Mock
}

// ParseParam provides a mock function with given fields: ctx
func (_m *IParamParser) ParseParam(ctx *gin.Context) ([]int, []string) {
	ret := _m.Called(ctx)

	var r0 []int
	if rf, ok := ret.Get(0).(func(*gin.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 []string
	if rf, ok := ret.Get(1).(func(*gin.Context) []string); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewIParamParser interface {
	mock.TestingT
	Cleanup(func())
}

// NewIParamParser creates a new instance of IParamParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIParamParser(t mockConstructorTestingTNewIParamParser) *IParamParser {
	mock := &IParamParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
