// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IReadAllRepository is an autogenerated mock type for the IReadAllRepository type
type IReadAllRepository[T interface{}] struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx, args
func (_m *IReadAllRepository[T]) All(ctx context.Context, args ...string) ([]*T, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*T
	if rf, ok := ret.Get(0).(func(context.Context, ...string) []*T); ok {
		r0 = rf(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*T)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIReadAllRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIReadAllRepository creates a new instance of IReadAllRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIReadAllRepository[T interface{}](t mockConstructorTestingTNewIReadAllRepository) *IReadAllRepository[T] {
	mock := &IReadAllRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
