name: Build Go & Push to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install Required Dependencies
        run: go mod tidy -compat=1.19
      - name: Build
        run: make build
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: pokewar-app
          # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
          package: ./build/
          publish-profile: ${{ secrets.AZURE_APP_SERVICE }}