name: Build Go & Push to Azure

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create Temps Dir
        run: mkdir "build/temps"
      - name: Create DB Dir
        run: mkdir "build/db"
      - name: Copy .db file
        run: xcopy /h db\local-data.db build\db
      - name: copy .env file
        run: xcopy /y/a .example.env build\.env*
      - name: Install Deps
        run: go mod vendor
      - name: Build
        run: go build -o build\pokewar.exe cmd\web\main.go
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: pokewar
          package: build/
          publish-profile: ${{ secrets.AZURE_APP_SERVICE }}
